baseURL = 'https://hammersandhives.net/'
languageCode = 'en-us'
title = 'Hammers and Hives'
theme = 'yue'

[module]
  [[module.imports]]
    path = 'https://github.com/CyrusYip/hugo-theme-yue'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

# [[menu.main]]
# name = "Troubleshooting"
# url = "/troubleshooting"
# weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3
